"""
Dashboard Data Collector and Decision Trigger
监控面板数据采集与决策触发后端

This module provides backend data collection and decision triggering for the MonitorDashboard frontend.
Addresses the AGI audit report finding: "监控面板仅前端UI，无后端数据采集、异常诊断、决策触发逻辑"
"""

import time
import logging
import threading
from typing import Dict, Any, List, Optional, Callable
from dataclasses import dataclass, field
from collections import defaultdict, deque
from datetime import datetime
import json

logger = logging.getLogger(__name__)

@dataclass
class MetricData:
    """Metric data point"""
    metric_name: str
    value: float
    timestamp: float
    tags: Dict[str, str]
    model_id: Optional[str] = None

@dataclass
class Alert:
    """Alert generated by monitoring"""
    alert_id: str
    alert_type: str
    severity: str  # 'info', 'warning', 'error', 'critical'
    message: str
    metric_name: str
    threshold: float
    current_value: float
    timestamp: float
    acknowledged: bool = False
    action_triggered: bool = False

@dataclass
class DecisionTrigger:
    """Decision trigger configuration"""
    trigger_id: str
    condition: Callable[[Dict[str, Any]], bool]
    action: Callable[[Dict[str, Any]], Dict[str, Any]]
    description: str
    enabled: bool = True

class DashboardDataCollector:
    """
    Backend data collector for MonitorDashboard
    
    Collects metrics from AGI models, detects anomalies, and triggers decisions.
    """
    
    def __init__(self, config: Dict[str, Any] = None):
        self.config = config or {}
        self.metrics_history = defaultdict(deque)  # metric_name -> deque of MetricData
        self.max_history_size = self.config.get('max_history_size', 1000)
        self.alerts = deque(maxlen=100)
        self.decision_triggers = []
        self.collection_interval = self.config.get('collection_interval', 5.0)  # seconds
        self.collection_thread = None
        self.running = False
        
        # Threshold configurations
        self.thresholds = {
            'cpu_usage': 80.0,
            'memory_usage': 85.0,
            'inference_latency': 1000.0,  # ms
            'error_rate': 0.05,
            'training_loss': 2.0,
            'knowledge_graph_size': 10000,
        }
        
        # Initialize decision triggers
        self._initialize_decision_triggers()
        
        logger.info("DashboardDataCollector initialized")
    
    def start_collection(self):
        """Start background data collection"""
        if self.running:
            logger.warning("Data collection already running")
            return
        
        self.running = True
        self.collection_thread = threading.Thread(target=self._collection_loop, daemon=True)
        self.collection_thread.start()
        logger.info("Started background data collection")
    
    def stop_collection(self):
        """Stop background data collection"""
        self.running = False
        if self.collection_thread:
            self.collection_thread.join(timeout=2.0)
        logger.info("Stopped background data collection")
    
    def _collection_loop(self):
        """Background collection loop"""
        while self.running:
            try:
                self._collect_metrics_from_models()
                self._detect_anomalies()
                self._check_decision_triggers()
            except Exception as e:
                logger.error(f"Error in collection loop: {e}")
            
            time.sleep(self.collection_interval)
    
    def _collect_metrics_from_models(self):
        """Collect metrics from registered models"""
        # Try to import model registry if available
        try:
            from core.model_registry import ModelRegistry
            registry = ModelRegistry()
            models = registry.get_all_models()
            
            for model_id, model_info in models.items():
                if hasattr(model_info, 'get_performance_metrics'):
                    metrics = model_info.get_performance_metrics()
                    for metric_name, value in metrics.items():
                        if isinstance(value, (int, float)):
                            self.add_metric(
                                metric_name=metric_name,
                                value=float(value),
                                tags={'model_id': model_id, 'source': 'model_registry'}
                            )
        except ImportError:
            # Fallback: collect system metrics
            self._collect_system_metrics()
    
    def _collect_system_metrics(self):
        """Collect system-level metrics as fallback"""
        import psutil
        import torch
        
        # CPU usage
        cpu_percent = psutil.cpu_percent(interval=0.1)
        self.add_metric('cpu_usage', cpu_percent, tags={'source': 'system'})
        
        # Memory usage
        memory = psutil.virtual_memory()
        self.add_metric('memory_usage', memory.percent, tags={'source': 'system'})
        
        # GPU memory if available
        if torch.cuda.is_available():
            gpu_memory = torch.cuda.memory_allocated() / torch.cuda.max_memory_allocated() * 100
            self.add_metric('gpu_memory_usage', gpu_memory, tags={'source': 'system', 'device': 'gpu'})
        
        # Timestamp
        self.add_metric('timestamp', time.time(), tags={'source': 'system'})
    
    def add_metric(self, metric_name: str, value: float, tags: Dict[str, str] = None, model_id: str = None):
        """Add a metric data point"""
        metric = MetricData(
            metric_name=metric_name,
            value=value,
            timestamp=time.time(),
            tags=tags or {},
            model_id=model_id
        )
        
        self.metrics_history[metric_name].append(metric)
        if len(self.metrics_history[metric_name]) > self.max_history_size:
            self.metrics_history[metric_name].popleft()
        
        # Check threshold for this metric
        self._check_threshold(metric_name, value, tags)
    
    def _check_threshold(self, metric_name: str, value: float, tags: Dict[str, str]):
        """Check if metric exceeds threshold and generate alert"""
        threshold = self.thresholds.get(metric_name)
        if threshold is not None and value > threshold:
            alert = Alert(
                alert_id=f"alert_{int(time.time())}_{metric_name}",
                alert_type='threshold_exceeded',
                severity='warning' if value < threshold * 1.5 else 'error',
                message=f"{metric_name} exceeded threshold: {value:.2f} > {threshold:.2f}",
                metric_name=metric_name,
                threshold=threshold,
                current_value=value,
                timestamp=time.time()
            )
            self.alerts.append(alert)
            logger.warning(f"Threshold alert: {alert.message}")
    
    def _detect_anomalies(self):
        """Detect anomalies in metric patterns"""
        # Simple anomaly detection: check for sudden spikes
        for metric_name, history in self.metrics_history.items():
            if len(history) < 10:
                continue
            
            recent = list(history)[-5:]
            older = list(history)[-10:-5]
            
            if not recent or not older:
                continue
            
            avg_recent = sum(m.value for m in recent) / len(recent)
            avg_older = sum(m.value for m in older) / len(older)
            
            if avg_older > 0 and avg_recent / avg_older > 2.0:  # Spike detection
                alert = Alert(
                    alert_id=f"anomaly_{int(time.time())}_{metric_name}",
                    alert_type='spike_detected',
                    severity='warning',
                    message=f"Sudden spike detected in {metric_name}: {avg_recent:.2f} vs {avg_older:.2f}",
                    metric_name=metric_name,
                    threshold=avg_older * 2.0,
                    current_value=avg_recent,
                    timestamp=time.time()
                )
                self.alerts.append(alert)
                logger.warning(f"Anomaly alert: {alert.message}")
    
    def _initialize_decision_triggers(self):
        """Initialize decision triggers"""
        # Trigger 1: High CPU usage -> trigger optimization
        def high_cpu_condition(data):
            cpu_metrics = data.get('cpu_usage', [])
            if cpu_metrics:
                latest = cpu_metrics[-1].value if cpu_metrics else 0
                return latest > self.thresholds['cpu_usage']
            return False
        
        def optimize_cpu_action(data):
            logger.info("Triggering CPU optimization decision")
            # In real implementation, this would call optimization model
            return {
                'decision': 'optimize_cpu',
                'action': 'reduce_model_complexity',
                'timestamp': time.time()
            }
        
        self.add_decision_trigger(
            trigger_id='high_cpu_optimization',
            condition=high_cpu_condition,
            action=optimize_cpu_action,
            description='Trigger optimization when CPU usage is high'
        )
        
        # Trigger 2: High error rate -> trigger retraining
        def high_error_condition(data):
            error_metrics = data.get('error_rate', [])
            if error_metrics:
                latest = error_metrics[-1].value if error_metrics else 0
                return latest > self.thresholds['error_rate']
            return False
        
        def retrain_action(data):
            logger.info("Triggering retraining decision")
            return {
                'decision': 'retrain_model',
                'action': 'start_retraining_process',
                'timestamp': time.time()
            }
        
        self.add_decision_trigger(
            trigger_id='high_error_retraining',
            condition=high_error_condition,
            action=retrain_action,
            description='Trigger retraining when error rate is high'
        )
    
    def add_decision_trigger(self, trigger_id: str, condition: Callable, action: Callable, description: str):
        """Add a decision trigger"""
        trigger = DecisionTrigger(
            trigger_id=trigger_id,
            condition=condition,
            action=action,
            description=description
        )
        self.decision_triggers.append(trigger)
        logger.info(f"Added decision trigger: {trigger_id}")
    
    def _check_decision_triggers(self):
        """Check all decision triggers and execute actions if conditions met"""
        for trigger in self.decision_triggers:
            if not trigger.enabled:
                continue
            
            # Prepare data for condition check
            data = {}
            for metric_name in self.thresholds.keys():
                data[metric_name] = list(self.metrics_history.get(metric_name, []))
            
            try:
                if trigger.condition(data):
                    logger.info(f"Decision trigger activated: {trigger.trigger_id}")
                    result = trigger.action(data)
                    result['trigger_id'] = trigger.trigger_id
                    result['activated_at'] = time.time()
                    
                    # Mark any related alerts as action triggered
                    for alert in self.alerts:
                        if alert.metric_name in data.keys() and not alert.action_triggered:
                            alert.action_triggered = True
                    
                    # Log decision
                    logger.info(f"Decision executed: {result}")
            except Exception as e:
                logger.error(f"Error executing decision trigger {trigger.trigger_id}: {e}")
    
    def get_metrics(self, metric_name: str = None, limit: int = 100) -> Dict[str, Any]:
        """Get metrics data for dashboard"""
        if metric_name:
            history = list(self.metrics_history.get(metric_name, []))[-limit:]
            return {
                'metric_name': metric_name,
                'data': [
                    {
                        'value': m.value,
                        'timestamp': m.timestamp,
                        'tags': m.tags,
                        'model_id': m.model_id
                    }
                    for m in history
                ],
                'count': len(history)
            }
        else:
            all_metrics = {}
            for name, history in self.metrics_history.items():
                all_metrics[name] = [
                    {
                        'value': m.value,
                        'timestamp': m.timestamp,
                        'tags': m.tags,
                        'model_id': m.model_id
                    }
                    for m in list(history)[-limit:]
                ]
            return all_metrics
    
    def get_alerts(self, unacknowledged_only: bool = False, limit: int = 50) -> List[Dict[str, Any]]:
        """Get alerts for dashboard"""
        alerts = []
        for alert in list(self.alerts)[-limit:]:
            if unacknowledged_only and alert.acknowledged:
                continue
            alerts.append({
                'alert_id': alert.alert_id,
                'alert_type': alert.alert_type,
                'severity': alert.severity,
                'message': alert.message,
                'metric_name': alert.metric_name,
                'threshold': alert.threshold,
                'current_value': alert.current_value,
                'timestamp': alert.timestamp,
                'acknowledged': alert.acknowledged,
                'action_triggered': alert.action_triggered
            })
        return alerts
    
    def acknowledge_alert(self, alert_id: str) -> bool:
        """Acknowledge an alert"""
        for alert in self.alerts:
            if alert.alert_id == alert_id:
                alert.acknowledged = True
                logger.info(f"Acknowledged alert: {alert_id}")
                return True
        return False
    
    def get_dashboard_summary(self) -> Dict[str, Any]:
        """Get dashboard summary data"""
        total_metrics = sum(len(history) for history in self.metrics_history.values())
        active_alerts = len([a for a in self.alerts if not a.acknowledged])
        
        # Calculate some statistics
        stats = {}
        for metric_name, history in self.metrics_history.items():
            if history:
                values = [m.value for m in history]
                stats[metric_name] = {
                    'current': values[-1] if values else 0,
                    'average': sum(values) / len(values) if values else 0,
                    'min': min(values) if values else 0,
                    'max': max(values) if values else 0,
                    'count': len(values)
                }
        
        return {
            'total_metrics': total_metrics,
            'active_alerts': active_alerts,
            'decision_triggers_count': len(self.decision_triggers),
            'metrics_count': len(self.metrics_history),
            'stats': stats,
            'collection_running': self.running,
            'timestamp': time.time()
        }


# Global instance for easy access
_dashboard_collector_instance = None

def get_dashboard_collector(config: Dict[str, Any] = None) -> DashboardDataCollector:
    """Get or create global dashboard collector instance"""
    global _dashboard_collector_instance
    if _dashboard_collector_instance is None:
        _dashboard_collector_instance = DashboardDataCollector(config)
    return _dashboard_collector_instance


# Example API integration (would be used in FastAPI route)
"""
from fastapi import APIRouter
router = APIRouter()
collector = get_dashboard_collector()

@router.get("/metrics")
async def get_metrics(metric_name: str = None, limit: int = 100):
    return collector.get_metrics(metric_name, limit)

@router.get("/alerts")
async def get_alerts(unacknowledged_only: bool = False):
    return collector.get_alerts(unacknowledged_only)

@router.post("/alerts/{alert_id}/acknowledge")
async def acknowledge_alert(alert_id: str):
    success = collector.acknowledge_alert(alert_id)
    return {"success": success}

@router.get("/dashboard/summary")
async def get_dashboard_summary():
    return collector.get_dashboard_summary()
"""